### PR TITLE
Added some articles about value objects

### PR DESCRIPTION
**Pull request by hkulekci**
"Persisting Value Objects in Doctrine" article added
"Value Objects, Immutable objects and Doctrine Embeddables" article added

### CODE REVIEW

**Comment by hkulekci** [comment]
ping @TomasVotruba

**Comment by TomasVotruba** [comment]
Thanks for adding these two. Know the Rosstuck one's.

I keep getting "Database Error" for second one.
http://aerendir.me/2015/07/03/php-and-doctrine-immutable-objects-value-objects-and-embeddables

**Comment by hkulekci** [comment]
@TomasVotruba hmm, it is working for me right now. Maybe, it would be great if there is a freezer for the web page. I did not get "Database Error" before for this site.

**Comment by TomasVotruba** [comment]
Mmm, am I doing something wrong?

Url: http://aerendir.me/2015/07/03/php-and-doctrine-immutable-objects-value-objects-and-embeddables

Result:

image

Chrome on Ubuntu

Maybe use Webarchive?

**Comment by hkulekci** [comment]
that is really interesting. I really don't understand why. I will change it with webarchive.

**Comment by hkulekci** [comment]
So I have learnt that archive.org is blocked in Turkey. :) Thankfully, there is VPN technology. The link updated @TomasVotruba

**Comment by TomasVotruba** [comment]
Thank you, great job! :+1:  

Interesting news about Turkey.

Link now works for me. Just scanned it quickly and it's quite nicely written and explained.

---

Btw, no need to write my name, since I'm subscribed to every repository I maintain and automatically get notifications about them.

**Comment by hkulekci** [comment]
Oh, ok. Sometimes people may close their notifications :) I want to make sure you get.

**Comment by TomasVotruba** [comment]
I see. But it makes only sense to ping somebody who is no in participants already (see right):

image

Those are who will get the message every time - now just you and me.

---

E.g. "Ping" is just fine to notice you. "Ping @hkulekci" does the same.

**Pull request merged**
