### PR TITLE
[Repository] add "How to use Repository with Doctrine as Service in S…

### PR DESCRIPTION
**Pull request by TomasVotruba**
…ymfony" post

This has been asked on SO like zilion times, so I took some time to write a post with solution

### CODE REVIEW

**Comment by hkulekci** [comment]
I totally missed this pr. Sorry @TomasVotruba

**Comment by hkulekci** [comment]
thanks.

**Comment by TomasVotruba** [comment]
You're welcome!

It happens to me too, Github kinda stopped notifing me about PRs on my repositories

**Comment by hkulekci** [comment]
I guess it may be all about watching. I start watching my own repositories :D this is a bit weird.

**Comment by TomasVotruba** [comment]
I wish ;) I watch them too for a long time, but still no notifications :cry:

**Pull request merged**
